import { PresetScenario } from './finance/types';

export const DEMO_PRESETS: PresetScenario[] = [
  {
    id: 'boglehead-dca',
    name: 'The Disciplined Boglehead (5-Year Canopy)',
    description: 'A thriving mature forest cultivated through consistent dollar-cost averaging into broad market index funds and bonds.',
    cashBalance: 1250,
    holdings: [
      {
        symbol: 'VOO',
        name: 'Vanguard S&P 500 ETF',
        assetClass: 'broad_market',
        shares: 65,
        costBasis: 24500,
        currentPrice: 485.5,
        firstPurchasedDate: '2020-04-15',
        lastPurchasedDate: '2025-01-10',
      },
      {
        symbol: 'SCHD',
        name: 'Schwab US Dividend Equity ETF',
        assetClass: 'dividend',
        shares: 110,
        costBasis: 7200,
        currentPrice: 82.3,
        firstPurchasedDate: '2021-02-18',
        lastPurchasedDate: '2024-11-20',
      },
      {
        symbol: 'BND',
        name: 'Vanguard Total Bond Market ETF',
        assetClass: 'bond',
        shares: 95,
        costBasis: 7600,
        currentPrice: 72.8,
        firstPurchasedDate: '2020-09-01',
        lastPurchasedDate: '2024-06-15',
      },
    ],
    transactions: [
      { id: 'tx-1', date: '2020-04-15', type: 'deposit', assetClass: 'cash', amount: 10000, note: 'Initial foundation' },
      { id: 'tx-2', date: '2020-04-16', type: 'buy', symbol: 'VOO', assetClass: 'broad_market', shares: 35, price: 260, amount: 9100 },
      { id: 'tx-3', date: '2020-09-01', type: 'deposit', assetClass: 'cash', amount: 8000, note: 'Annual bonus DCA' },
      { id: 'tx-4', date: '2020-09-02', type: 'buy', symbol: 'BND', assetClass: 'bond', shares: 95, price: 80, amount: 7600 },
      { id: 'tx-5', date: '2021-02-18', type: 'deposit', assetClass: 'cash', amount: 8000, note: 'Dividend allocation' },
      { id: 'tx-6', date: '2021-02-19', type: 'buy', symbol: 'SCHD', assetClass: 'dividend', shares: 110, price: 65.45, amount: 7200 },
      { id: 'tx-7', date: '2022-06-15', type: 'deposit', assetClass: 'cash', amount: 6000, note: 'Bear market DCA' },
      { id: 'tx-8', date: '2022-06-16', type: 'buy', symbol: 'VOO', assetClass: 'broad_market', shares: 16, price: 370, amount: 5920 },
      { id: 'tx-9', date: '2024-01-10', type: 'deposit', assetClass: 'cash', amount: 6000, note: 'Regular DCA' },
      { id: 'tx-10', date: '2024-01-11', type: 'buy', symbol: 'VOO', assetClass: 'broad_market', shares: 14, price: 420, amount: 5880 },
    ],
  },
  {
    id: 'winter-drawdown',
    name: 'Winter Crash Soil (Bear Market Opportunity)',
    description: 'Experiencing market turbulence. Snow blankets the soil, turning market drawdowns into discount seedling opportunities.',
    cashBalance: 4200,
    holdings: [
      {
        symbol: 'VTI',
        name: 'Vanguard Total Stock Market',
        assetClass: 'broad_market',
        shares: 40,
        costBasis: 10800,
        currentPrice: 215.0, // temporarily down from cost
        firstPurchasedDate: '2022-01-05',
        lastPurchasedDate: '2022-03-10',
      },
      {
        symbol: 'BND',
        name: 'Vanguard Total Bond ETF',
        assetClass: 'bond',
        shares: 50,
        costBasis: 4250,
        currentPrice: 71.5,
        firstPurchasedDate: '2022-01-05',
        lastPurchasedDate: '2022-01-05',
      },
    ],
    transactions: [
      { id: 'tx-w1', date: '2022-01-05', type: 'deposit', assetClass: 'cash', amount: 15000, note: 'Pre-correction deposit' },
      { id: 'tx-w2', date: '2022-01-06', type: 'buy', symbol: 'VTI', assetClass: 'broad_market', shares: 40, price: 270, amount: 10800 },
      { id: 'tx-w3', date: '2022-01-06', type: 'buy', symbol: 'BND', assetClass: 'bond', shares: 50, price: 85, amount: 4250 },
      { id: 'tx-w4', date: '2022-10-15', type: 'deposit', assetClass: 'cash', amount: 4200, note: 'Dry powder reserve' },
    ],
  },
  {
    id: 'fresh-sprout',
    name: 'First Sprout (Day 1 Seedling)',
    description: 'A modest start. A tiny oak sprout just emerged from fertile soil with the very first paycheck deposit.',
    cashBalance: 250,
    holdings: [
      {
        symbol: 'VOO',
        name: 'Vanguard S&P 500 ETF',
        assetClass: 'broad_market',
        shares: 1.5,
        costBasis: 720,
        currentPrice: 485.0,
        firstPurchasedDate: '2025-01-01',
        lastPurchasedDate: '2025-01-01',
      },
    ],
    transactions: [
      { id: 'tx-s1', date: '2025-01-01', type: 'deposit', assetClass: 'cash', amount: 1000, note: 'My first investment' },
      { id: 'tx-s2', date: '2025-01-02', type: 'buy', symbol: 'VOO', assetClass: 'broad_market', shares: 1.5, price: 480, amount: 720 },
    ],
  },
];
